# Generated by Django 4.2.5 on 2023-10-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='noimage.png', upload_to='image/%Y', verbose_name='Изображение'),
        ),
    ]
