# Generated by Django 4.2.5 on 2023-10-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='/image/noimage.png', upload_to='image/%Y', verbose_name='Изображение'),
        ),
    ]
